bootstrap.servers=localhost:9092
bootstrap.servers.docker=broker:29092
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
group.id=slow-poll-group
auto.offset.reset=earliest
