version: "3"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "${PWD}/.data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "${PWD}/.data:/bitnami"
      - "${PWD}:/lab-root"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=DOCKER:PLAINTEXT,HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=DOCKER://:9092,HOST://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=DOCKER://kafka:9092,HOST://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=DOCKER
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
